# Generated by Django 5.1.1 on 2024-10-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectModels', '0002_userinfodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profimage', models.ImageField(blank=True, null=True, upload_to='profileImages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileimage', to='ProjectModels.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfoData',
        ),
    ]
